import {
  IconApps,
  IconBarcode,
  IconBrandAppstore,
  IconBrandGithub,
  IconBrandTiktok,
  IconBuildingStore,
  IconBuildingWarehouse,
  IconCategory,
  IconChartArrowsVertical,
  IconChartLine,
  IconContract,
  IconDeviceAnalytics,
  IconDiscount,
  IconList,
  IconPackage,
  IconPoint,
  IconRobot,
  IconShield,
  IconShieldCheck,
  IconSpider,
  IconTools,
  IconTransfer,
  IconUserCheck,
  IconUsers,
  IconUsersGroup,
} from '@tabler/icons-react';
import {
  AlertTriangle,
  ArrowRight,
  Bot,
  Check,
  ChevronLeft,
  ChevronRight,
  CircuitBoardIcon,
  Command,
  CreditCard,
  File,
  FileText,
  HelpCircle,
  Image,
  Laptop,
  LayoutDashboardIcon,
  Loader2,
  LogIn,
  LucideIcon,
  Moon,
  MoreVertical,
  Pizza,
  Plus,
  Settings,
  ShoppingBag,
  SunMedium,
  Trash,
  Truck,
  User,
  User2Icon,
  UserX2Icon,
  X,
} from 'lucide-react';

export type Icon = LucideIcon;

export const Icons = {
  category: IconCategory,
  analytics: IconDeviceAnalytics,
  dashboard: LayoutDashboardIcon,
  logo: Command,
  login: LogIn,
  close: X,
  profile: User2Icon,
  spinner: Loader2,
  kanban: CircuitBoardIcon,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  employee: UserX2Icon,
  post: FileText,
  page: File,
  media: Image,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  shoppingBag: ShoppingBag,
  discount: IconDiscount,
  list: IconList,
  truck: Truck,
  gitHub: IconBrandGithub,
  check: Check,
  spider: IconSpider,
  tools: IconTools,
  transfer: IconTransfer,
  store: IconBuildingStore,
  apps: IconApps,
  appstore: IconBrandAppstore,
  bot: Bot,
  robot: IconRobot,
  users: IconUsers,
  shield: IconShield,
  shieldCheck: IconShieldCheck,
  userCheck: IconUserCheck,
  usersGroup: IconUsersGroup,
  contract: IconContract,
  warehouse: IconBuildingWarehouse,
  package: IconPackage,
  tiktok: IconBrandTiktok,
  barcode: IconBarcode,
  arrowsV: IconChartArrowsVertical,
  point: IconPoint,
  chartLine: IconChartLine,
};
